### ISSUE TITLE
FileSystemException: An async operation is currently pending

### ISSUE THREAD

**Issue by brenomenosso** [lesnitsky/flutter_localstorage#102] opened 2023-09-12 20:03 UTC
Exception has occurred.
FileSystemException (FileSystemException: An async operation is currently pending, path = '/data/user/0/com.app.app')

Method Exception:

  Future setKey(String key, dynamic data) async {
    await _checkIsReady();

    if (isReady) {
      await _localStorage!.setItem(key, data);
    }
  }

**Comment by brenomenosso** [comment] 2023-09-12 20:05
@felix-mittermeier help ?

**Comment by peazz** [comment] 2023-10-06 10:51
This is a problem for me on too on iOS v16.

Crashalytics is reporting this consistently across many users. I've checked the entire codebase to ensure everything is being awaited properly;

I have tried two ways to initialise too;

`storage.ready.then((success) =>AppStorage(storage)`

and 

`await storage.ready
AppStorage(storage);
`

**Comment by felix-mittermeier** [comment] 2023-10-06 11:48
Just replace the package inside your pub spec.yaml file with

```
localstorage:
    git:
      url: https://github.com/Ocell-io/flutter_localstorage.git
```

And the problem should be fixed :-)

**Comment by peazz** [comment] 2023-10-06 11:49
Id suggest this is a system level bug then beyond any packages control 🤷‍♂️

**Comment by felix-mittermeier** [comment] 2023-10-06 11:52
Not sure what you mean? The issue is that in real life usage two operations at the same time try to read/write something to the local storage. If this happens, the system error is thrown. So in my fork of the package (as mentioned above) I ensured that it will never try to do two operations simultaneously but after each other.

**Comment by peazz** [comment] 2023-10-06 11:54
Well you didn’t state it was a fork at all, you just said replace it with this - not very helpful.

I’ve already migrated to shared preferences.

Good luck.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by felix-mittermeier** [comment] 2023-10-06 11:58
I mean if it has the same package name, then it's always a fork. But sorry, just wanted to help. This issue was already explained multiple times in this issue: https://github.com/lesnitsky/flutter_localstorage/issues/56#issuecomment-800651187

I was tagged in a comment above, that's why I answered 😅

**Comment by brenomenosso** [comment] 2023-10-06 14:24
Thank you @felix-mittermeier, because error: 

Error (Xcode): lib/services/localstorage_database.dart:1:8: Error: Error when reading '../../../.pub-cache/git/flutter_localstorage-be405ab1476da74ad4ca58458f93bbc7cddd2c02/lib/localstorage.dart': No such file or directory

pod install e pod update ?

**Comment by felix-mittermeier** [comment] 2023-10-06 14:26
@brenomenosso Please provide more details what you did, what happened and what you tried. Otherwise I don't think I can help you

**Comment by brenomenosso** [comment] 2023-10-06 14:32
I just added the git part as mentioned above to pubspec.... I tried pod install and pod update, because I'm running and testing on an iPhone


<img width="584" alt="Captura de Tela 2023-10-06 às 11 30 53" src="https://github.com/lesnitsky/flutter_localstorage/assets/39105140/ccfc7066-8a97-419d-b7b6-996f3b07f420">

**Comment by felix-mittermeier** [comment] 2023-10-06 14:34
Normally you don't have to run the pod command newly after changing the package. Did you already try `flutter clean` and `flutter pub get` ?

**Comment by brenomenosso** [comment] 2023-10-06 14:39
I try, cleaning

**Comment by brenomenosso** [comment] 2023-10-06 14:49
not working, import is correct ?

<img width="1074" alt="Captura de Tela 2023-10-06 às 11 48 26" src="https://github.com/lesnitsky/flutter_localstorage/assets/39105140/9a440e21-c180-4aa7-8691-b6c4d81b97ab">

**Comment by felix-mittermeier** [comment] 2023-10-06 14:56
Yeah that's correct. Hmm this looks like you pub cache is invalid 🤔

Maybe you can try to delete the pubspec.lock file and then run `flutter pub get` again.

**Comment by brenomenosso** [comment] 2023-10-06 14:58
ok, I will do this

**Comment by brenomenosso** [comment] 2023-10-06 16:08
not working. By any chance, do you have a print of your pubspec.lock of what it would look like?

**Comment by lesnitsky** [comment] 2024-04-01 18:16
v5 is synchronous now.

**Closed as completed by lesnitsky** 2024-04-01 18:16 UTC
